### ISSUE TITLE
MLabel引起线程问题崩溃

### ISSUE THREAD

**Issue by flg1217** [phenom-films/dayu_widgets#35]
MLabel的__init__
self.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction | QtCore.Qt.LinksAccessibleByMouse)
在houdini的18.5， py2.7运行容易出现线程问题而引起奔溃
例如在一个widget类中创建另一个widget窗口

**Comment by FXTD-ODYSSEY** [comment]
劳烦提供一下 崩溃的案例代码

**Comment by FXTD-ODYSSEY** [comment]
![image](https://user-images.githubusercontent.com/40897360/145993558-dce72d6b-c44e-448a-a0a3-f0e0a38b53c8.png)

默认的案例是可以跑通的。

**Comment by flg1217** [comment]
谢谢回复。
定位到问题了，我的情况是pdgobject的回调函数调用了MLabel的setText，从而引发以下异常

Qt Warn: QObject: Cannot create children for a parent that is in a different thread.
(Parent is MLabel(0x11dccd480), parent's thread is QThread(0x41dd7590), current thread is QThread(0x83aab930)
Qt Warn: QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0x83aab990), parent's thread is QThread(0x83aab930), current thread is QThread(0x41dd7590)
7252: Fatal error: Segmentation fault

备注掉MLabel的QtCore.Qt.TextBrowserInteraction | QtCore.Qt.LinksAccessibleByMouse刚好能避免崩溃
但是这样跨线程的方式本来应该也是会出问题的，我现在改成子线程调用信号来更新了。

**Comment by FXTD-ODYSSEY** [comment]
好的
