### ISSUE TITLE
当前版本在3dsmax运行的问题

### ISSUE THREAD

**Issue by flg1217** [phenom-films/dayu_widgets#37]
我用的是max 2017,当前版本的dayu_widgets是使用Qt.py来导入的，然后我在max里面一引入Qt就直接崩溃了
有没有什么好的解决方案

**Comment by FXTD-ODYSSEY** [comment]
请问崩溃有报错提示吗？

我这边测试没有问题
![image](https://user-images.githubusercontent.com/40897360/146193084-2b5852d8-5aac-4bf2-8615-98fd1a900209.png)
![image](https://user-images.githubusercontent.com/40897360/146193878-5d04c8eb-39fc-4022-ae98-b17864090e96.png)

**Comment by flg1217** [comment]
没有提示，就是异常崩溃，我查到是Qt.py的问题，在max的python脚本里面输入import Qt，一运行就已经崩掉了，
请问你那边的Qt.py是什么版本的，我这边试了几台电脑都是这样

**Comment by FXTD-ODYSSEY** [comment]
win7 没有测试，可能是存在系统不兼容

**Comment by flg1217** [comment]
嗯，各种现实问题导致没法再用更高的版本了。。
我排查到是max的pyside里面那个qthelp dll导入异常，不纠结了，我简单的改了一下Qt.py的代码跳过这个模块了
