### ISSUE TITLE
great work！有没有提供支持pyqt5版本的计划

### ISSUE THREAD

**Issue by kanbang** [phenom-films/dayu_widgets#4]
有没有提供支持pyqt5版本的计划

**Comment by smallsong** [comment]
期待pyqt5版本

**Comment by wsii** [comment]
把dayu_widgets\qt\__init__.py 中的 import 改成
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PySide2.QtSvg import QSvgRenderer

还要把dayu_path库下下来，和dayu_widgets 放在同级目录下，就可以使用了，

**Comment by muyr** [comment]
已经有好心人使用Qt.py 给做了兼容。大家试试看
