### ISSUE TITLE
MPage的页数信号错误

### ISSUE THREAD

**Issue by flg1217** [phenom-films/dayu_widgets#41]
MPage的页数信号错误
每次切换Page size的时候，信号回传的值都为上一次的值

![MPage01](https://user-images.githubusercontent.com/11772959/176808963-468f7ac5-6571-41d6-b8d6-6cf739761ba4.png)
![MPage02](https://user-images.githubusercontent.com/11772959/176808964-b725b8a5-fca3-4414-9c9b-250142c0ecb7.png)

排查了一下是在Page size切换信号发出来的时候，page_size_selected的数值还未更新
把`self._change_page_size_button.sig_value_changed.connect(self._emit_page_changed)`调到 
`self.bind(
            "page_size_selected",
            self._change_page_size_button,
            "value",
            signal="sig_value_changed",
        )`
这里之后就可以正常了

**Comment by muyr** [comment]
感谢！已经更新了

**Comment by muyr** [comment]
另外，确实一个人精力有限，非常欢迎你贡献代码，这里有 [如何贡献代码](https://github.com/phenom-films/dayu_widgets#%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81) 的步骤
