### ISSUE TITLE
Is the TagWidget missing?

### ISSUE THREAD

**Issue by PaulSchweizer** [phenom-films/dayu_widgets#5]
Hi guys, this looks like great work! 
I'd be especially interested in the TagWidget but can't seem to find it in the code. If I am I overlooking it, could you please guide me to where I can find it?
Thanks!

**Comment by muyr** [comment]
https://github.com/muyr/dayu_widgets_tag

**Comment by PaulSchweizer** [comment]
Thanks a lot @muyr and thanks again for the sharing your work!
