### ISSUE TITLE
MMessage 显示位置错误

### ISSUE THREAD

**Issue by wuqingjing2010** [phenom-films/dayu_widgets#54]
在DCC 中 显示Widget窗口 将 MMessage 显示在该窗口中央存在 MMessage widget 偏移问题

修改前
![image](https://user-images.githubusercontent.com/27915914/198948667-d5c38825-0a84-4fc6-9f96-f2bf4ad411ed.png)

修改后
![image](https://user-images.githubusercontent.com/27915914/198948336-573c3132-fb11-4250-8c6f-31f225b3966b.png)

修复方法：
dayu_widgets/message 133 行
![image](https://user-images.githubusercontent.com/27915914/198949936-50f69a39-4fe1-43a2-a117-c4a6d9f41cb3.png)

**Comment by loonghao** [comment]
@wuqingjing2010 
欢迎提PR，帮忙更新这个

**Comment by linkcc32** [comment]
大佬牛逼，这个是咋算的

**Comment by muyr** [comment]
> 在DCC 中 显示Widget窗口 将 MMessage 显示在该窗口中央存在 MMessage widget 偏移问题
> 
> 修改前 ![image](https://user-images.githubusercontent.com/27915914/198948667-d5c38825-0a84-4fc6-9f96-f2bf4ad411ed.png)
> 
> 修改后 ![image](https://user-images.githubusercontent.com/27915914/198948336-573c3132-fb11-4250-8c6f-31f225b3966b.png)
> 
> 修复方法： dayu_widgets/message 133 行 ![image](https://user-images.githubusercontent.com/27915914/198949936-50f69a39-4fe1-43a2-a117-c4a6d9f41cb3.png)

但是 demo 里面的就跑了
![image](https://github.com/phenom-films/dayu_widgets/assets/1860334/7340c43f-a414-406f-91e9-dbea2ae9487e)

**Comment by muyr** [comment]
https://github.com/phenom-films/dayu_widgets/pull/96 

@wuqingjing2010 来试试呗
