### ISSUE TITLE
少了一个叫Qt的package， 或者需求的安装环境怎样的？

### ISSUE THREAD

**Issue by EzerbelCN** [phenom-films/dayu_widgets#61]
我自己蒙了一个叫Qt的package但是还是没有蒙混过关
![image](https://user-images.githubusercontent.com/66873183/232192559-b974b2b5-8e56-42c5-a5f0-27263386e559.png)
![image](https://user-images.githubusercontent.com/66873183/232192879-151431be-a43d-4332-93c5-b9bf4c724e34.png)

**Comment by loonghao** [comment]
如果是开发的话，你需要通过

```
poetry install
```
去安装依赖，这个[Qt.py](https://github.com/mottosso/Qt.py)是一个第三方库
