### ISSUE TITLE
样式表固定颜色疑问

### ISSUE THREAD

**Issue by MrRuben3** [phenom-films/dayu_widgets#86]
**Describe the bug**
dayu_widgets/static/main.qss 样式表内有两处颜色是固定色，当背景色太深时，字体颜色太黑看不清

**To Reproduce**
1. 运行examples/demo.py
2. 选择左侧任意项

**Expected behavior**
希望可以换成自动颜色（深色背景白字，浅色背景黑字）

**Screenshots**
![Snipaste_2024-06-13_16-33-48](https://github.com/phenom-films/dayu_widgets/assets/44090667/3a8059cb-fe1c-4455-a1fe-bec9409cd9c7)

![image](https://github.com/phenom-films/dayu_widgets/assets/44090667/fce0ad39-d4b3-46ed-ab74-0e6d205a9eb7)

**Comment by muyr** [comment]
收到。最近会把qss文件里面的固定颜色和固定尺寸的地方修复为动态读取theme

**Comment by muyr** [comment]
https://github.com/phenom-films/dayu_widgets/pull/91

已经 fix 了
